<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251218233226 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE perfil_card ADD category_id INT NOT NULL');
        $this->addSql('ALTER TABLE perfil_card DROP category');
        $this->addSql('ALTER TABLE perfil_card ADD CONSTRAINT FK_86B1B78612469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_86B1B78612469DE2 ON perfil_card (category_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE category');
        $this->addSql('ALTER TABLE perfil_card DROP CONSTRAINT FK_86B1B78612469DE2');
        $this->addSql('DROP INDEX IDX_86B1B78612469DE2');
        $this->addSql('ALTER TABLE perfil_card ADD category VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE perfil_card DROP category_id');
    }
}
