<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251218214859 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE perfil_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(255) NOT NULL, answer VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE perfil_tip (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tip VARCHAR(255) NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_52B17C434ACC9A20 ON perfil_tip (card_id)');
        $this->addSql('CREATE TABLE tips_revealed (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, card_id INT NOT NULL, tip_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A5259F09A76ED395 ON tips_revealed (user_id)');
        $this->addSql('CREATE INDEX IDX_A5259F094ACC9A20 ON tips_revealed (card_id)');
        $this->addSql('CREATE INDEX IDX_A5259F09476C47F6 ON tips_revealed (tip_id)');
        $this->addSql('ALTER TABLE perfil_tip ADD CONSTRAINT FK_52B17C434ACC9A20 FOREIGN KEY (card_id) REFERENCES perfil_card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tips_revealed ADD CONSTRAINT FK_A5259F09A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tips_revealed ADD CONSTRAINT FK_A5259F094ACC9A20 FOREIGN KEY (card_id) REFERENCES perfil_card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tips_revealed ADD CONSTRAINT FK_A5259F09476C47F6 FOREIGN KEY (tip_id) REFERENCES perfil_tip (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE perfil_tip DROP CONSTRAINT FK_52B17C434ACC9A20');
        $this->addSql('ALTER TABLE tips_revealed DROP CONSTRAINT FK_A5259F09A76ED395');
        $this->addSql('ALTER TABLE tips_revealed DROP CONSTRAINT FK_A5259F094ACC9A20');
        $this->addSql('ALTER TABLE tips_revealed DROP CONSTRAINT FK_A5259F09476C47F6');
        $this->addSql('DROP TABLE perfil_card');
        $this->addSql('DROP TABLE perfil_tip');
        $this->addSql('DROP TABLE tips_revealed');
    }
}
